os: linux
language: python
sudo: false
python: 3.6
env:
- PKG_NAME=pus
script:
- bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis.sh)
notifications:
  email:
    recipients:
    - danilo.horta@gmail.com
    on_success: never
    on_failure: always
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: VCjpjLNP6ekSCV6av2PflWdso3m+4W2FeRdzxzCQ+0dqUcKiTDDfod/rDeLOX6a4oPDu9JdUXyBwYfWrIW/M/d0ytkfmCgVkTxEiCZqm3wrdVULwEpRnWI/7tqy5rpjreXtlLU4owrqrYhXcjsINZl4g/NhRZghLDa0tzT3LjuaniGnjxIp9JDyWRzWZKRlapghVcZbUz6j/rHtc/UJeNKffa66db5F5wkqdcJnoK/rlrgZaicZOAMmIbQFJxmGN7DGFdi1XGLQpz9R+N+rk9OghNYde8+wUDwfVWGWlggtiN6HC95belu/6HxIaG6qn3vKIV1ooN33sb5UIanD5yUUmB1tycX5iHz5/HeXkyKxLWOEP7nu+6fSntP//e/XROzn3Z5qQQOq5R783A1HSOt4YVQMX9d7GRhW7Da1MEUvFCVmGA33Xi8I89OvThaEXSaDKSUcPLrs+uFfbVxPF1r9zGdCnUNYC5zBI6uxxSA5mPX+cokwfGP84X5dDrueiReIf60wjkCnTF4HipqzwFSZJOzPboh985fuH0oQdQ6DZERLX/DJh7yCZgz+tb2UQvQ/GCC/YmvrtijVo41MXQLt0eB5SBMHDNW6NNHP5RP0EG9Qz+CbBGwajPpqwhjuWGNR0nZ1G2+P6OpiuXlz/iMsBEW06vJYpdSRZosQpowo=
  on:
    tags: true
    repo: limix/pus
    branch: master
