os: linux
language: python
sudo: false
python: 3.6
env:
- PKG_NAME=pus
script:
- bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis.sh)
notifications:
  email:
    recipients:
    - danilo.horta@gmail.com
    on_success: never
    on_failure: always
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: vfGk1nvPwJ2Ufu4wmJl2bYyGadFYKpryd4IwreHgnsDiI/tvCjTQIf2hXYag3YinOQZkhFSi7AsRqiBhneQi2CMNpxcecWfM1YhYE45byFBdj/B6LiFXpIZ4vkQ32ZHDHoNLM3oIYJ+PVxUUIMXr474rV4CslwRNd4zyqBJQTQnpjJbN04maeIUMRxAw5jc1zkzQqk21WRp6hPZuEsyW7FaEnhsrSG+7nxoRg6YaaDH09dmQcXIGTWsmDvuPdD+xlQXBVv7kro8QPi69ioE+hfKOLcvdYPtf3/W+DFVvzdXaGZrHKzgSuVKo1mUFis6EUrx2z/1vwtPhNgfuJHmXJsYw+w/cKY/9MoTD+o4r76N2Ku1JwYGcYBVQXipgWRqC0DM8NYk6YspObVuzvVSorrcefYfn9tSVJ0Mo+kGrtzE8Lv8g+X53djH2/R+a8Xd1t2X3b+MC/7om1t9IDkpkbjvU75VEF5kjXJtaBJsG4G8dYSsjIIiFkMdlah08JGO89UE9LhmJklJmcnyIvikGeYzZ2oiVPcfmUyAbmAQX2++ls5isZIuJx3ITrC883lwV19r3YSeCmxvgNZQFT2iq1xa2MbK6kgoOqZBL3KigLUEN2+I2+9D5zD3lb5ETMO+Xy3aYM1FFV75En0SgcGIiwYOuCnUa/kz+ZkW9/HfBvCA=
  on:
    tags: true
    repo: horta/pus
